"""create core reference tables

Revision ID: 059804f37a25
Revises: 
Create Date: 2026-05-09 12:43:49.936611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059804f37a25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('count_unit', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_store_info',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('store_item_name', sa.String(length=255), nullable=True),
    sa.Column('count_unit', sa.String(length=64), nullable=True),
    sa.Column('par', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'store_id', name='uq_item_store')
    )
    op.create_index(op.f('ix_item_store_info_item_id'), 'item_store_info', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_store_info_store_id'), 'item_store_info', ['store_id'], unique=False)
    op.create_table('item_vendor_info',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_sku', sa.String(length=255), nullable=True),
    sa.Column('vendor_item_name', sa.String(length=255), nullable=True),
    sa.Column('purchase_unit', sa.String(length=64), nullable=True),
    sa.Column('pack_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'vendor_id', 'vendor_sku', name='uq_item_vendor_sku')
    )
    op.create_index(op.f('ix_item_vendor_info_item_id'), 'item_vendor_info', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_vendor_info_vendor_id'), 'item_vendor_info', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_vendor_info_vendor_id'), table_name='item_vendor_info')
    op.drop_index(op.f('ix_item_vendor_info_item_id'), table_name='item_vendor_info')
    op.drop_table('item_vendor_info')
    op.drop_index(op.f('ix_item_store_info_store_id'), table_name='item_store_info')
    op.drop_index(op.f('ix_item_store_info_item_id'), table_name='item_store_info')
    op.drop_table('item_store_info')
    op.drop_table('vendors')
    op.drop_table('stores')
    op.drop_table('items')
    # ### end Alembic commands ###