"""expand store and vendor records

Revision ID: 3492134fef13
Revises: eea46108ad86
Create Date: 2026-05-25 10:26:20.029167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3492134fef13'
down_revision: Union[str, Sequence[str], None] = 'eea46108ad86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('general_manager', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('inventory_clerk', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('phone_number', sa.String(length=64), nullable=True))
    op.add_column('stores', sa.Column('special_notes', sa.Text(), nullable=False))
    op.add_column('vendors', sa.Column('order_format', sa.String(length=64), nullable=False))
    op.add_column('vendors', sa.Column('special_notes', sa.Text(), nullable=False))
    op.add_column('vendors', sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('vendors', sa.Column('min_order_cases', sa.Integer(), nullable=False))
    op.add_column('vendors', sa.Column('internal_contacts_json', sa.JSON(), nullable=False))
    op.add_column('vendors', sa.Column('ordering_json', sa.JSON(), nullable=False))
    op.add_column('vendors', sa.Column('store_ids_json', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'store_ids_json')
    op.drop_column('vendors', 'ordering_json')
    op.drop_column('vendors', 'internal_contacts_json')
    op.drop_column('vendors', 'min_order_cases')
    op.drop_column('vendors', 'min_order_value')
    op.drop_column('vendors', 'special_notes')
    op.drop_column('vendors', 'order_format')
    op.drop_column('stores', 'special_notes')
    op.drop_column('stores', 'phone_number')
    op.drop_column('stores', 'address')
    op.drop_column('stores', 'inventory_clerk')
    op.drop_column('stores', 'general_manager')
    # ### end Alembic commands ###