"""add item measurement fields

Revision ID: 79f2797bd94f
Revises: f934230e8f45
Create Date: 2026-05-27 08:43:21.543673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f2797bd94f'
down_revision: Union[str, Sequence[str], None] = 'f934230e8f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('count_unit_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('items', sa.Column('count_unit_measure', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('custom_each_name', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('each_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('items', sa.Column('each_measure', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('weight_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('items', sa.Column('weight_measure', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('volume_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('items', sa.Column('volume_measure', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'volume_measure')
    op.drop_column('items', 'volume_quantity')
    op.drop_column('items', 'weight_measure')
    op.drop_column('items', 'weight_quantity')
    op.drop_column('items', 'each_measure')
    op.drop_column('items', 'each_quantity')
    op.drop_column('items', 'custom_each_name')
    op.drop_column('items', 'count_unit_measure')
    op.drop_column('items', 'count_unit_quantity')
    # ### end Alembic commands ###