"""add orders

Revision ID: 9da5b205adf7
Revises: 3492134fef13
Create Date: 2026-05-26 10:18:29.509690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da5b205adf7'
down_revision: Union[str, Sequence[str], None] = '3492134fef13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_orders_vendor_id'), 'orders', ['vendor_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('item_vendor_info_id', sa.String(length=32), nullable=True),
    sa.Column('source_item_name', sa.String(length=255), nullable=True),
    sa.Column('item_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('vendor_sku_snapshot', sa.String(length=255), nullable=True),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('moved_to_order_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_vendor_info_id'], ['item_vendor_info.id'], ),
    sa.ForeignKeyConstraint(['moved_to_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_item_id'), 'order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_lines_item_vendor_info_id'), 'order_lines', ['item_vendor_info_id'], unique=False)
    op.create_index(op.f('ix_order_lines_moved_to_order_id'), 'order_lines', ['moved_to_order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_moved_to_order_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_item_vendor_info_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_item_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_orders_vendor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###