"""add source_vendor_sku to order lines

Revision ID: beb5a6e1ee0c
Revises: 9da5b205adf7
Create Date: 2026-05-26 11:48:16.962437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb5a6e1ee0c'
down_revision: Union[str, Sequence[str], None] = '9da5b205adf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_lines', sa.Column('source_vendor_sku', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_lines', 'source_vendor_sku')
    # ### end Alembic commands ###