"""sync item_store_info

Revision ID: eea46108ad86
Revises: 059804f37a25
Create Date: 2026-05-25 09:10:33.263512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea46108ad86'
down_revision: Union[str, Sequence[str], None] = '059804f37a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_store_info', 'store_item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_store_info', sa.Column('store_item_name', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###