# -----------------------------------
#             BASE ERROR
# -----------------------------------
class WorkBotBaseError(Exception):
    def __init__(self, message: str, *, cause: Exception|None=None):
        super().__init__(message)
        self.message = message
        self.cause = cause


# -----------------------------------
#            INFRA ERRORS
# -----------------------------------
class InfraError(WorkBotBaseError): ...

class SeleniumError(InfraError): ...
class SeleniumTimeoutError(SeleniumError): ...

class FileSystemError(InfraError): ...
class FileReadError(FileSystemError): ...
class FileWriteError(FileSystemError): ...
class StoragePermissionError(FileSystemError): ...

# -----------------------------------
#             REPO ERRORS
# -----------------------------------
class RepositoryError(WorkBotBaseError): ...
class FileLoadError(RepositoryError): ...
class FileSaveError(RepositoryError): ...
class RepositoryDataError(RepositoryError): ...


# -----------------------------------
#        DOMAIN SERVICES ERRORS
# -----------------------------------
class DomainError(WorkBotBaseError): ...

class OrderNotFoundError(DomainError): ...
class OrderAlreadyExistsError(DomainError): ...
class OrderInvalidError(DomainError): ...
class DownloadFileMissing(DomainError): ...


# -----------------------------------
#     WORKBOT APPLICATION ERRORS
# -----------------------------------
class WorkBotError(WorkBotBaseError): ...

