from __future__ import annotations

from typing import Protocol

from workbot_core.domain.models.item import Item
from workbot_core.domain.models.store import Store
from workbot_core.domain.models.vendor import Vendor


class StoreRepository(Protocol):
    def get_by_id(self, store_id: str) -> Store | None: ...

    def get_by_name(self, name: str) -> Store | None: ...

    def list_all(self) -> list[Store]: ...

    def list_active(self) -> list[Store]: ...

    def save(self, store: Store) -> None: ...

    def delete(self, store_id: str) -> None: ...


class VendorRepository(Protocol):
    def get_by_id(self, vendor_id: str) -> Vendor | None: ...

    def get_by_name(self, name: str) -> Vendor | None: ...

    def list_all(self) -> list[Vendor]: ...

    def list_active(self) -> list[Vendor]: ...

    def save(self, vendor: Vendor) -> None: ...

    def delete(self, vendor_id: str) -> None: ...


class ItemRepository(Protocol):
    def get_by_id(self, item_id: str) -> Item | None: ...

    def get_by_name(self, name: str) -> Item | None: ...

    def list_all(self) -> list[Item]: ...

    def list_active(self) -> list[Item]: ...

    def save(self, item: Item) -> None: ...

    def delete(self, item_id: str) -> None: ...