from __future__ import annotations
from pathlib import Path
from typing import Protocol, TypeVar

T = TypeVar("T")

class GenericFilePort(Protocol[T]):
    
    def get_directory(self) -> Path: ...
    def get_file_path(self, obj: T, format: str) -> Path: ...
    def parse_filename(self, filename: str) -> dict: ...
    def list_files(self, pattern: str = "*") -> list[Path]: ...
    def read_from_path(self, path: Path): ...
    def save(self, obj: T, format: str = 'xlsx') -> Path: ...
    def remove(self, path: Path) -> None: ...
    def move(self, src: Path, dest: Path, overwrite: bool = False) -> None: ...
    def find(self, **criteria) -> list[T]: ...
