from __future__ import annotations
from pathlib import Path
from typing import Protocol, TypeVar, Generic, Optional, List, Any, Iterable

T = TypeVar('T')

class Repository(Protocol, Generic[T]):
    '''Abstracts persistence operations (CRUD).'''
    def get(self, key: str) -> T: ...
    def list_all(self) -> List[T]: ...
    def save(self, obj: T) -> None: ...
    def remove(self, key: str) -> None: ...

# General Infra
class BlobStore(Protocol):
    '''
    Minimal filesystem-like surface. Can be implemented by local FS, S3, etc.
    Paths are always absolute when passed in here.
    '''
    # write / read
    def write_bytes(self, path: Path, data: bytes, *, overwrite: bool = False) -> None: ...
    def read_bytes(self, path: Path) -> bytes: ...

    # file operations
    def exists(self, path: Path) -> bool: ...
    def remove(self, path: Path) -> None: ...
    def move(self, src: Path, dest: Path, *, overwrite: bool = False) -> None: ...

    # discovery
    def list_paths(self, base: Path, pattern: str = "*") -> list[Path]: ...
    def iter_files(self, root: Path) -> Iterable[Path]: ...
    def ensure_dir(self, path: Path) -> None: ...



