from __future__ import annotations
from pathlib import Path
from typing import Protocol, TypeVar, Generic, Optional, List, Any, Iterable

T = TypeVar('T')

# Domain-necessity Generics
class Serializer(Protocol, Generic[T]):
    '''Turn domain objects into bytes (and back).'''
    def preferred_format(self) -> str: ...
    def dumps(self, obj: T, format: Optional[str] = None, context: dict | None = None) -> bytes: ...
    def loads(self, data: bytes, format: Optional[str] = None) -> T: ...
    # Optional fast path for local files
    def load_path(self, path: Path) -> T: ...

    def get_formatter(self, fmt: str): ...

class Namer(Protocol, Generic[T]):
    '''Decide where & how files are named on disk.'''
    def base_dir(self) -> Path: ...
    def filename(self, obj: T, *, format: str) -> str: ...
    def parse_filename_for_metadata(self, filename: str) -> dict[str, Any]: ...
    def path_for(self, obj: T) -> Path: ...
    def parse_path_metadata(self, path: Path) -> dict[str, Any]:
        return self.parse_filename_for_metadata(path.name)


class Repository(Protocol, Generic[T]):
    '''Abstracts persistence operations (CRUD).'''
    def get(self, key: str) -> T: ...
    def list_all(self) -> List[T]: ...
    def save(self, obj: T) -> None: ...
    def remove(self, key: str) -> None: ...

# General Infra
class BlobStore(Protocol):
    '''
    Minimal filesystem-like surface. Can be implemented by local FS, S3, etc.
    Paths are always absolute when passed in here.
    '''
    # write / read
    def write_bytes(self, path: Path, data: bytes, *, overwrite: bool = False) -> None: ...
    def read_bytes(self, path: Path) -> bytes: ...

    # file operations
    def exists(self, path: Path) -> bool: ...
    def remove(self, path: Path) -> None: ...
    def move(self, src: Path, dest: Path, *, overwrite: bool = False) -> None: ...

    # discovery
    def list_paths(self, base: Path, pattern: str = "*") -> list[Path]: ...
    def iter_files(self, root: Path) -> Iterable[Path]: ...
    def ensure_dir(self, path: Path) -> None: ...



