from __future__ import annotations
from typing import Protocol, List
from pathlib import Path
from backend.domain.models import Order, Vendor, Store


class LocatorPort(Protocol):
    """
    Unified read-only interface for cross-domain data access.

    Concrete implementations (e.g., DataAccessFacade) can wrap
    multiple repositories behind this interface.
    """

    # ---- Domain Queries ----

    # Orders
    def get_order(self, vendor: str, store: str, date: str | None = None) -> Order: ...
    def list_orders(self) -> List[Order]: ...
    def list_orders_by_vendor(self, vendor: str) -> List[Order]: ...
    def list_orders_by_store(self, store: str) -> List[Order]: ...

    # Vendors
    def get_vendor(self, name: str) -> Vendor: ...
    def list_vendors(self) -> List[Vendor]: ...

    # Stores
    def get_store(self, name: str) -> Store: ...
    def list_stores(self) -> List[Store]: ...

    # ---- File Path Utilities ----
    def path_for_order(self, order: Order, format: str = "xlsx") -> Path: ...
    def path_for_vendor(self, vendor: Vendor, format: str = "json") -> Path: ...
    def path_for_store(self, store: Store, format: str = "json") -> Path: ...

    # ---- Cross-domain Convenience ----
    def vendor_orders(self, vendor_name: str) -> List[Order]: ...
    def store_orders(self, store_name: str) -> List[Order]: ...
    def vendor_order_paths(self, vendor_name: str, format: str = "pdf") -> List[Path]: ...
