from __future__ import annotations
from typing import Protocol, List
from backend.domain.models import Order, Vendor, Store, Transfer
from backend.app.ports.generic import Repository
from pathlib import Path

class OrderRepository(Repository[Order], Protocol):
    def get(self, store: str, vendor: str, date: str | None = None) -> Order: ...
    def list_all(self) -> List[Order]: ...
    def remove(self, store: str, vendor: str, date: str | None = None) -> None: ...
    def save(self, order: Order) -> int: ...

    def list_by_vendor(self, vendor: str) -> List[Order]: ...
    def list_by_store(self, store: str) -> List[Order]: ...
    
    def generate_vendor_upload_file(self, order: Order, context: dict | None = None) -> None: ...
    def ingest_downloaded_attachment(self, order: Order, src_path: Path, kind: str) -> None: ...

    def generate_combined_orders_file(self, orders: List[Order]) -> None: ...

    def generate_natalies_splits(self, orders: List[Order]) -> List[Order]: ...

class VendorRepository(Repository[Vendor], Protocol):
    def get(self, vendor_name: str) -> Vendor: ...
    def list_all(self) -> list[Vendor]: ...
    def save(self, vendor: Vendor) -> None: ...
    def remove(self, vendor_name: str) -> None: ...

class StoreRepository(Repository[Store], Protocol):
    def get(self, store_name: str) -> Store: ...
    def list_all(self) -> List[Store]: ...
    def save(self, store: Store) -> None: ...
    def remove(self, store_name: str) -> None: ...
    
class TransferRepository(Repository[Transfer], Protocol):
    def get(self, origin_store: str, destination_store: str, date: str | None = None ): ...
    def list_all(self) -> List[Transfer]: ...
    def save(self, transfer: Transfer) -> None: ...
    def remove(self, origin_store: str, destination_store: str, date: str | None = None): ...